# Generated by Django 5.0 on 2026-04-08 17:19

import companies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=companies.validators.logo_upload_path, validators=[companies.validators.validate_logo_size]),
        ),
    ]
