# Generated by Django 5.0 on 2026-04-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
