# Generated by Django 5.0 on 2026-04-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_created_at_alter_company_description_and_more'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='profession',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='professions.profession', verbose_name='Профессия'),
        ),
    ]
