# Generated by Django 5.0 on 2026-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_vacancy_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience_required',
            field=models.CharField(choices=[('with_experience', 'С опытом'), ('without_experience', 'Без опыта')], default='with_experience', max_length=50, verbose_name='Тип требований'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_type',
            field=models.CharField(choices=[('week', 'Раз в неделю'), ('month', 'Раз в месяц'), ('twice_monthly', '2 раза в месяц'), ('daily', 'Ежедневно'), ('hourly', 'По часам')], default='month', max_length=50, verbose_name='Тип выплаты'),
        ),
    ]
