# Generated by Django 5.0 on 2026-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_feedbackcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='experience',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный опыт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный опыт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная заработная плата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная заработная плата'),
        ),
    ]
