# Generated by Django 5.0 on 2026-04-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_vacancy_experience_vacancy_experience_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vacancy', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vacancy', to='companies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Избранная вакансия',
                'verbose_name_plural': 'Избранные вакансии',
            },
        ),
        migrations.AddConstraint(
            model_name='favoritevacancy',
            constraint=models.UniqueConstraint(fields=('user', 'vacancy'), name='unique_favorite_vacancy'),
        ),
    ]
