# Generated by Django 5.0 on 2026-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_favoritevacancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург'), ('kazan', 'Казань'), ('novosibirsk', 'Новосибирск'), ('yekaterinburg', 'Екатеринбург'), ('sochi', 'Сочи')], default='moscow', max_length=30, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица'),
        ),
    ]
