# Generated by Django 5.0 on 2026-05-07 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_vacancy_city_vacancy_street'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Скрыто')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by_user', to='companies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Скрытая вакансия',
                'verbose_name_plural': 'Скрытые вакансии',
            },
        ),
        migrations.AddConstraint(
            model_name='hiddenvacancy',
            constraint=models.UniqueConstraint(fields=('user', 'vacancy'), name='unique_hidden_vacancy'),
        ),
    ]
