# Generated by Django 5.0 on 2026-05-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_hiddenvacancy_hiddenvacancy_unique_hidden_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcompany',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='companies.vacancy', verbose_name='Вакансия'),
        ),
    ]
