# Generated by Django 5.0 on 2026-05-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="reason",
            field=models.TextField(
                help_text="Опишите причину жалобы", verbose_name="Причина"
            ),
        ),
    ]
