# Generated by Django 5.0 on 2026-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_alter_complaint_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Заработная плата",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_from",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Минимальная заработная плата",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_to",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Максимальная заработная плата",
            ),
        ),
    ]
