# Generated by Django 5.0 on 2026-04-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
        ('resumes', '0002_alter_resume_created_at_alter_resume_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='professions.profession', verbose_name='Профессия'),
        ),
    ]
