# Generated by Django 5.0 on 2026-04-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_vacancy_experience_vacancy_experience_from_and_more'),
        ('resumes', '0003_resume_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_views', to='companies.company', verbose_name='Компания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_views', to='resumes.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
            },
        ),
        migrations.AddConstraint(
            model_name='resumeview',
            constraint=models.UniqueConstraint(fields=('company', 'resume', 'date'), name='unique_resume_view_per_day'),
        ),
    ]
