# Generated by Django 5.0 on 2026-05-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_resumeview_resumeview_unique_resume_view_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="О себе, навыки, компетенции",
                null=True,
                verbose_name="Общая информация",
            ),
        ),
    ]
