# Generated by Django 5.0 on 2026-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_resume_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="desired_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Желаемая зарплата",
            ),
        ),
    ]
