# Generated by Django 5.0 on 2026-04-20 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0009_remove_vacancy_experience_vacancy_experience_from_and_more'),
        ('resumes', '0003_resume_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='Сопроводительное письмо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('viewed', 'Просмотрено'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='resumes.resume', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='companies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('vacancy', 'resume'), name='unique_response_per_vacancy_resume'),
        ),
    ]
