# Generated by Django 5.0 on 2026-04-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('companies', '0009_remove_vacancy_experience_vacancy_experience_from_and_more'),
        ('resumes', '0003_resume_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Текст приглашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приглашения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='resumes.resume', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='companies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('vacancy', 'resume'), name='unique_invitation_per_vacancy_resume'),
        ),
    ]
