# Generated by Django 5.0 on 2026-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург'), ('kazan', 'Казань'), ('novosibirsk', 'Новосибирск'), ('yekaterinburg', 'Екатеринбург'), ('sochi', 'Сочи')], default='moscow', max_length=30, verbose_name='Город'),
        ),
    ]
