# Generated by Django 5.0 on 2026-05-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
