# Generated by Django 5.0 on 2026-05-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
    ]
